### ISSUE TITLE
#hidden-citations leaves a series of dots before the bibliography

### ISSUE THREAD

**Issue by ironupiwada** [pklaschka/typst-hidden-bib#4]
Lots of undesired dots appear after using #hidden-citations. They are highlighted before the bibliography, as demonstrated in the supplied screenshots:

![image](https://github.com/user-attachments/assets/ed866fe1-0f35-422f-9053-c2fe8e5df872)
![image](https://github.com/user-attachments/assets/71011523-c982-4e41-b2b1-f8ecc17ee8fb)

**Comment by pklaschka** [comment]
Hi @ironupiwada, thanks for bringing this to my attention.

In this case, the issue are the commas in the `#hidden-citations[]` block. The "dots" are the commas, if you leave them out, they should be gone:

```typ
#import "@preview/hidden-bib:0.1.1": *

#hidden-citations[
  @klaschka_wuspace_2023
  @meier_zur_2011
]

#bibliography("literature.bib")
```

What is happening under the hood is that within a `hidden-citations` block, **only the citations themselves** get hidden. As the brackets `[]` open a new content block, it's the same as outside the block, allowing you to
1. write the shorthand `#cite` syntax (`@xxx`), and
2. theoretically, any other content.
What's crucial here is (2.), as this means that the commas in your text get interpreted as content, which in turn gets rendered by Typst. Due to the way hiding the citations works in the library, this adds a line break between each of them. And that, then, explains the output you're seeing.

Best regards,
Zuri
